spring.application.name=api-quota-app

# DATABASE CONFIG
spring.datasource.url=jdbc:mysql://localhost:3306/api_quota_app
spring.datasource.username=root
spring.datasource.password=root

# JPA CONFIG
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# THYMELEAF
spring.thymeleaf.cache=false